const noteBaseUrl = 'static/notes/'

export default {
  major: [
    {id: 1, name: 'C2', keyCode: '90', key: 'z', url: noteBaseUrl + 'a49.mp3', type: 'white'},
    {id: 2, name: 'D2', keyCode: '88', key: 'x', url: noteBaseUrl + 'a50.mp3', type: 'white'},
    {id: 3, name: 'E2', keyCode: '74', key: 'j', url: noteBaseUrl + 'a51.mp3', type: 'white'},
    {id: 4, name: 'F2', keyCode: '86', key: 'v', url: noteBaseUrl + 'a52.mp3', type: 'white'},
    {id: 5, name: 'G2', keyCode: '66', key: 'b', url: noteBaseUrl + 'a53.mp3', type: 'white'},
    {id: 6, name: 'A2', keyCode: '188', key: ',', url: noteBaseUrl + 'a54.mp3', type: 'white'},
    {id: 7, name: 'B2', keyCode: '71', key: 'g', url: noteBaseUrl + 'a55.mp3', type: 'white'},
    {id: 8, name: 'C3', keyCode: '87', key: 'w', url: noteBaseUrl + 'a56.mp3', type: 'white'},
    {id: 9, name: 'D3', keyCode: '85', key: 'u', url: noteBaseUrl + 'a57.mp3', type: 'white'},
    {id: 10, name: 'E3', keyCode: '76', key: 'l', url: noteBaseUrl + 'a48.mp3', type: 'white'},
    {id: 26, name: 'F3', keyCode: '82', key: 'r', url: noteBaseUrl + 'a81.mp3', type: 'white'},
    {id: 32, name: 'G3', keyCode: '83', key: 's', url: noteBaseUrl + 'a87.mp3', type: 'white'},
    {id: 14, name: 'A3', keyCode: '73', key: 'i', url: noteBaseUrl + 'a69.mp3', type: 'white'},
    {id: 27, name: 'B3', keyCode: '65', key: 'a', url: noteBaseUrl + 'a82.mp3', type: 'white'},
    {id: 29, name: 'C4', keyCode: '69', key: 'e', url: noteBaseUrl + 'a84.mp3', type: 'white'},
    {id: 34, name: 'D4', keyCode: '84', key: 't', url: noteBaseUrl + 'a89.mp3', type: 'white'},
    {id: 30, name: 'E4', keyCode: '79', key: 'o', url: noteBaseUrl + 'a85.mp3', type: 'white'},
    {id: 18, name: 'F4', keyCode: '78', key: 'n', url: noteBaseUrl + 'a73.mp3', type: 'white'},
    {id: 24, name: 'G4', keyCode: '72', key: 'h', url: noteBaseUrl + 'a79.mp3', type: 'white'},
    {id: 25, name: 'A4', keyCode: '68', key: 'd', url: noteBaseUrl + 'a80.mp3', type: 'white'},
    {id: 10, name: 'B4', keyCode: '67', key: 'c', url: noteBaseUrl + 'a65.mp3', type: 'white'},
    {id: 28, name: 'C5', keyCode: '77', key: 'm', url: noteBaseUrl + 'a83.mp3', type: 'white'},
    {id: 13, name: 'D5', keyCode: '70', key: 'f', url: noteBaseUrl + 'a68.mp3', type: 'white'},
    {id: 15, name: 'E5', keyCode: '89', key: 'y', url: noteBaseUrl + 'a70.mp3', type: 'white'},
    {id: 16, name: 'F5', keyCode: '80', key: 'p', url: noteBaseUrl + 'a71.mp3', type: 'white'},
    {id: 17, name: 'G5', keyCode: '190', key: '.', url: noteBaseUrl + 'a72.mp3', type: 'white'},
    {id: 19, name: 'A5', keyCode: '75', key: 'k', url: noteBaseUrl + 'a74.mp3', type: 'white'},
    {id: 20, name: 'B5', keyCode: '186', key: ';', url: noteBaseUrl + 'a75.mp3', type: 'white'},
    {id: 21, name: 'C6', keyCode: '81', key: 'q', url: noteBaseUrl + 'a76.mp3', type: 'white'},
    {id: 35, name: 'D6', keyCode: '191', key: '/', url: noteBaseUrl + 'a90.mp3', type: 'white'},
    {id: 33, name: 'E6', keyCode: '200', key: '', url: noteBaseUrl + 'a88.mp3', type: 'white'},
    {id: 12, name: 'F6', keyCode: '201', key: '', url: noteBaseUrl + 'a67.mp3', type: 'white'},
    {id: 31, name: 'G6', keyCode: '202', key: '', url: noteBaseUrl + 'a86.mp3', type: 'white'},
    {id: 11, name: 'A6', keyCode: '203', key: '', url: noteBaseUrl + 'a66.mp3', type: 'white'},
    {id: 23, name: 'B6', keyCode: '204', key: '', url: noteBaseUrl + 'a78.mp3', type: 'white'},
    {id: 22, name: 'C7', keyCode: '205', key: '', url: noteBaseUrl + 'a77.mp3', type: 'white'},
  
    {id: 36, name: 'C#2', keyCode: 'b49', key: '', url: noteBaseUrl + 'b49.mp3', type: 'black'},
    {id: 37, name: 'D#2', keyCode: 'b50', key: '', url: noteBaseUrl + 'b50.mp3', type: 'black'},
    {id: 38, name: 'F#2', keyCode: 'b52', key: '', url: noteBaseUrl + 'b52.mp3', type: 'black'},
    {id: 39, name: 'G#2', keyCode: 'b53', key: '', url: noteBaseUrl + 'b53.mp3', type: 'black'},
    {id: 40, name: 'A#2', keyCode: 'b54', key: '', url: noteBaseUrl + 'b54.mp3', type: 'black'},
    {id: 41, name: 'C#3', keyCode: 'b56', key: '', url: noteBaseUrl + 'b56.mp3', type: 'black'},
    {id: 42, name: 'D#3', keyCode: 'b57', key: '', url: noteBaseUrl + 'b57.mp3', type: 'black'},
    {id: 43, name: 'F#3', keyCode: 'b81', key: '', url: noteBaseUrl + 'b81.mp3', type: 'black'},
    {id: 44, name: 'G#3', keyCode: 'b87', key: '', url: noteBaseUrl + 'b87.mp3', type: 'black'},
    {id: 45, name: 'A#3', keyCode: 'b69', key: '', url: noteBaseUrl + 'b69.mp3', type: 'black'},
    {id: 46, name: 'C#4', keyCode: 'b84', key: '', url: noteBaseUrl + 'b84.mp3', type: 'black'},
    {id: 47, name: 'D#4', keyCode: 'b89', key: '', url: noteBaseUrl + 'b89.mp3', type: 'black'},
    {id: 48, name: 'F#4', keyCode: 'b73', key: '', url: noteBaseUrl + 'b73.mp3', type: 'black'},
    {id: 49, name: 'G#4', keyCode: 'b79', key: '', url: noteBaseUrl + 'b79.mp3', type: 'black'},
    {id: 50, name: 'A#4', keyCode: 'b80', key: '', url: noteBaseUrl + 'b80.mp3', type: 'black'},
    {id: 51, name: 'C#5', keyCode: 'b83', key: '', url: noteBaseUrl + 'b83.mp3', type: 'black'},
    {id: 52, name: 'D#5', keyCode: 'b68', key: '', url: noteBaseUrl + 'b68.mp3', type: 'black'},
    {id: 53, name: 'F#5', keyCode: 'b71', key: '', url: noteBaseUrl + 'b71.mp3', type: 'black'},
    {id: 54, name: 'G#5', keyCode: 'b72', key: '', url: noteBaseUrl + 'b72.mp3', type: 'black'},
    {id: 55, name: 'A#5', keyCode: 'b74', key: '', url: noteBaseUrl + 'b74.mp3', type: 'black'},
    {id: 56, name: 'C#6', keyCode: 'b76', key: '', url: noteBaseUrl + 'b76.mp3', type: 'black'},
    {id: 57, name: 'D#6', keyCode: 'b90', key: '', url: noteBaseUrl + 'b90.mp3', type: 'black'},
    {id: 58, name: 'F#6', keyCode: 'b67', key: '', url: noteBaseUrl + 'b67.mp3', type: 'black'},
    {id: 59, name: 'G#6', keyCode: 'b86', key: '', url: noteBaseUrl + 'b86.mp3', type: 'black'},
    {id: 60, name: 'A#6', keyCode: 'b66', key: '', url: noteBaseUrl + 'b66.mp3', type: 'black'},
  ],
  whole_tone: [
    {id: 1, name: 'C2', keyCode: '74', key: 'j', url: noteBaseUrl + 'a49.mp3', type: 'white'},
    {id: 2, name: 'D2', keyCode: '86', key: 'v', url: noteBaseUrl + 'a50.mp3', type: 'white'},
    {id: 3, name: 'E2', keyCode: '66', key: 'b', url: noteBaseUrl + 'a51.mp3', type: 'white'},
    {id: 4, name: 'F2', keyCode: 'b59', key: '', url: noteBaseUrl + 'a52.mp3', type: 'white'},
    {id: 5, name: 'G2', keyCode: 'b60', key: '', url: noteBaseUrl + 'a53.mp3', type: 'white'},
    {id: 6, name: 'A2', keyCode: 'b61', key: '', url: noteBaseUrl + 'a54.mp3', type: 'white'},
    {id: 7, name: 'B2', keyCode: 'b62', key: '', url: noteBaseUrl + 'a55.mp3', type: 'white'},
    {id: 8, name: 'C3', keyCode: '85', key: 'u', url: noteBaseUrl + 'a56.mp3', type: 'white'},
    {id: 9, name: 'D3', keyCode: '76', key: 'l', url: noteBaseUrl + 'a57.mp3', type: 'white'},
    {id: 10, name: 'E3', keyCode: '82', key: 'r', url: noteBaseUrl + 'a48.mp3', type: 'white'},
    {id: 26, name: 'F3', keyCode: 'b63', key: '', url: noteBaseUrl + 'a81.mp3', type: 'white'},
    {id: 32, name: 'G3', keyCode: 'b64', key: '', url: noteBaseUrl + 'a87.mp3', type: 'white'},
    {id: 14, name: 'A3', keyCode: 'b65', key: '', url: noteBaseUrl + 'a69.mp3', type: 'white'},
    {id: 27, name: 'B3', keyCode: 'b66', key: '', url: noteBaseUrl + 'a82.mp3', type: 'white'},
    {id: 29, name: 'C4', keyCode: '69', key: 'e', url: noteBaseUrl + 'a84.mp3', type: 'white'},
    {id: 34, name: 'D4', keyCode: '84', key: 't', url: noteBaseUrl + 'a89.mp3', type: 'white'},
    {id: 30, name: 'E4', keyCode: '79', key: 'o', url: noteBaseUrl + 'a85.mp3', type: 'white'},
    {id: 18, name: 'F4', keyCode: 'b67', key: '', url: noteBaseUrl + 'a73.mp3', type: 'white'},
    {id: 24, name: 'G4', keyCode: 'b68', key: '', url: noteBaseUrl + 'a79.mp3', type: 'white'},
    {id: 25, name: 'A4', keyCode: 'b69', key: '', url: noteBaseUrl + 'a80.mp3', type: 'white'},
    {id: 10, name: 'B4', keyCode: 'b70', key: '', url: noteBaseUrl + 'a65.mp3', type: 'white'},
    {id: 28, name: 'C5', keyCode: '67', key: 'c', url: noteBaseUrl + 'a83.mp3', type: 'white'},
    {id: 13, name: 'D5', keyCode: '77', key: 'm', url: noteBaseUrl + 'a68.mp3', type: 'white'},
    {id: 15, name: 'E5', keyCode: '70', key: 'f', url: noteBaseUrl + 'a70.mp3', type: 'white'},
    {id: 16, name: 'F5', keyCode: 'b71', key: '', url: noteBaseUrl + 'a71.mp3', type: 'white'},
    {id: 17, name: 'G5', keyCode: 'b72', key: '', url: noteBaseUrl + 'a72.mp3', type: 'white'},
    {id: 19, name: 'A5', keyCode: 'b73', key: '', url: noteBaseUrl + 'a74.mp3', type: 'white'},
    {id: 20, name: 'B5', keyCode: 'b74', key: '', url: noteBaseUrl + 'a75.mp3', type: 'white'},
    {id: 21, name: 'C6', keyCode: '75', key: 'k', url: noteBaseUrl + 'a76.mp3', type: 'white'},
    {id: 35, name: 'D6', keyCode: '186', key: ';', url: noteBaseUrl + 'a90.mp3', type: 'white'},
    {id: 33, name: 'E6', keyCode: '81', key: 'q', url: noteBaseUrl + 'a88.mp3', type: 'white'},
    {id: 12, name: 'F6', keyCode: 'b75', key: '', url: noteBaseUrl + 'a67.mp3', type: 'white'},
    {id: 31, name: 'G6', keyCode: 'b76', key: '', url: noteBaseUrl + 'a86.mp3', type: 'white'},
    {id: 11, name: 'A6', keyCode: 'b77', key: '', url: noteBaseUrl + 'a66.mp3', type: 'white'},
    {id: 23, name: 'B6', keyCode: 'b78', key: '', url: noteBaseUrl + 'a78.mp3', type: 'white'},
    {id: 22, name: 'C7', keyCode: 'b79', key: '', url: noteBaseUrl + 'a77.mp3', type: 'white'},

    {id: 36, name: 'C#2', keyCode: 'b49', key: '', url: noteBaseUrl + 'b49.mp3', type: 'black'},
    {id: 37, name: 'D#2', keyCode: 'b50', key: '', url: noteBaseUrl + 'b50.mp3', type: 'black'},
    {id: 38, name: 'F#2', keyCode: '188', key: ',', url: noteBaseUrl + 'b52.mp3', type: 'black'},
    {id: 39, name: 'G#2', keyCode: '71', key: 'g', url: noteBaseUrl + 'b53.mp3', type: 'black'},
    {id: 40, name: 'A#2', keyCode: '87', key: 'w', url: noteBaseUrl + 'b54.mp3', type: 'black'},
    {id: 41, name: 'C#3', keyCode: 'b51', key: '', url: noteBaseUrl + 'b56.mp3', type: 'black'},
    {id: 42, name: 'D#3', keyCode: 'b52', key: '', url: noteBaseUrl + 'b57.mp3', type: 'black'},
    {id: 43, name: 'F#3', keyCode: '83', key: 's', url: noteBaseUrl + 'b81.mp3', type: 'black'},
    {id: 44, name: 'G#3', keyCode: '73', key: 'i', url: noteBaseUrl + 'b87.mp3', type: 'black'},
    {id: 45, name: 'A#3', keyCode: '65', key: 'a', url: noteBaseUrl + 'b69.mp3', type: 'black'},
    {id: 46, name: 'C#4', keyCode: 'b53', key: '', url: noteBaseUrl + 'b84.mp3', type: 'black'},
    {id: 47, name: 'D#4', keyCode: 'b54', key: '', url: noteBaseUrl + 'b89.mp3', type: 'black'},
    {id: 48, name: 'F#4', keyCode: '78', key: 'n', url: noteBaseUrl + 'b73.mp3', type: 'black'},
    {id: 49, name: 'G#4', keyCode: '72', key: 'h', url: noteBaseUrl + 'b79.mp3', type: 'black'},
    {id: 50, name: 'A#4', keyCode: '68', key: 'd', url: noteBaseUrl + 'b80.mp3', type: 'black'},
    {id: 51, name: 'C#5', keyCode: 'b55', key: '', url: noteBaseUrl + 'b83.mp3', type: 'black'},
    {id: 52, name: 'D#5', keyCode: 'b56', key: '', url: noteBaseUrl + 'b68.mp3', type: 'black'},
    {id: 53, name: 'F#5', keyCode: '89', key: 'y', url: noteBaseUrl + 'b71.mp3', type: 'black'},
    {id: 54, name: 'G#5', keyCode: '80', key: 'p', url: noteBaseUrl + 'b72.mp3', type: 'black'},
    {id: 55, name: 'A#5', keyCode: '190', key: '.', url: noteBaseUrl + 'b74.mp3', type: 'black'},
    {id: 56, name: 'C#6', keyCode: 'b57', key: '', url: noteBaseUrl + 'b76.mp3', type: 'black'},
    {id: 57, name: 'D#6', keyCode: 'b58', key: '', url: noteBaseUrl + 'b90.mp3', type: 'black'},
    {id: 58, name: 'F#6', keyCode: '191', key: '/', url: noteBaseUrl + 'b67.mp3', type: 'black'},
    {id: 59, name: 'G#6', keyCode: '88', key: 'x', url: noteBaseUrl + 'b86.mp3', type: 'black'},
    {id: 60, name: 'A#6', keyCode: '90', key: 'z', url: noteBaseUrl + 'b66.mp3', type: 'black'},
  ],
  chromatic: [
    {id: 1, name: 'C2', keyCode: 'b49', key: '', url: noteBaseUrl + 'a49.mp3', type: 'white'},
    {id: 2, name: 'D2', keyCode: 'b50', key: '', url: noteBaseUrl + 'a50.mp3', type: 'white'},
    {id: 3, name: 'E2', keyCode: 'b51', key: '', url: noteBaseUrl + 'a51.mp3', type: 'white'},
    {id: 4, name: 'F2', keyCode: 'b52', key: '', url: noteBaseUrl + 'a52.mp3', type: 'white'},
    {id: 5, name: 'G2', keyCode: 'b53', key: '', url: noteBaseUrl + 'a53.mp3', type: 'white'},
    {id: 6, name: 'A2', keyCode: 'b54', key: '', url: noteBaseUrl + 'a54.mp3', type: 'white'},
    {id: 7, name: 'B2', keyCode: '88', key: 'x', url: noteBaseUrl + 'a55.mp3', type: 'white'},
    {id: 8, name: 'C3', keyCode: '74', key: 'j', url: noteBaseUrl + 'a56.mp3', type: 'white'},
    {id: 9, name: 'D3', keyCode: '66', key: 'b', url: noteBaseUrl + 'a57.mp3', type: 'white'},
    {id: 10, name: 'E3', keyCode: '71', key: 'g', url: noteBaseUrl + 'a48.mp3', type: 'white'},
    {id: 26, name: 'F3', keyCode: '87', key: 'w', url: noteBaseUrl + 'a81.mp3', type: 'white'},
    {id: 32, name: 'G3', keyCode: '76', key: 'l', url: noteBaseUrl + 'a87.mp3', type: 'white'},
    {id: 14, name: 'A3', keyCode: '83', key: 's', url: noteBaseUrl + 'a69.mp3', type: 'white'},
    {id: 27, name: 'B3', keyCode: '65', key: 'a', url: noteBaseUrl + 'a82.mp3', type: 'white'},
    {id: 29, name: 'C4', keyCode: '69', key: 'e', url: noteBaseUrl + 'a84.mp3', type: 'white'},
    {id: 34, name: 'D4', keyCode: '79', key: 'o', url: noteBaseUrl + 'a89.mp3', type: 'white'},
    {id: 30, name: 'E4', keyCode: '72', key: 'h', url: noteBaseUrl + 'a85.mp3', type: 'white'},
    {id: 18, name: 'F4', keyCode: '68', key: 'd', url: noteBaseUrl + 'a73.mp3', type: 'white'},
    {id: 24, name: 'G4', keyCode: '77', key: 'm', url: noteBaseUrl + 'a79.mp3', type: 'white'},
    {id: 25, name: 'A4', keyCode: '89', key: 'y', url: noteBaseUrl + 'a80.mp3', type: 'white'},
    {id: 10, name: 'B4', keyCode: '190', key: '.', url: noteBaseUrl + 'a65.mp3', type: 'white'},
    {id: 28, name: 'C5', keyCode: '186', key: ';', url: noteBaseUrl + 'a83.mp3', type: 'white'},
    {id: 13, name: 'D5', keyCode: '81', key: 'q', url: noteBaseUrl + 'a68.mp3', type: 'white'},
    {id: 15, name: 'E5', keyCode: '200', key: '', url: noteBaseUrl + 'a70.mp3', type: 'white'},
    {id: 16, name: 'F5', keyCode: '201', key: '', url: noteBaseUrl + 'a71.mp3', type: 'white'},
    {id: 17, name: 'G5', keyCode: '202', key: '', url: noteBaseUrl + 'a72.mp3', type: 'white'},
    {id: 19, name: 'A5', keyCode: '203', key: '', url: noteBaseUrl + 'a74.mp3', type: 'white'},
    {id: 20, name: 'B5', keyCode: '204', key: '', url: noteBaseUrl + 'a75.mp3', type: 'white'},
    {id: 21, name: 'C6', keyCode: '205', key: '', url: noteBaseUrl + 'a76.mp3', type: 'white'},
    {id: 35, name: 'D6', keyCode: '206', key: '', url: noteBaseUrl + 'a90.mp3', type: 'white'},
    {id: 33, name: 'E6', keyCode: '207', key: '', url: noteBaseUrl + 'a88.mp3', type: 'white'},
    {id: 12, name: 'F6', keyCode: '208', key: '', url: noteBaseUrl + 'a67.mp3', type: 'white'},
    {id: 31, name: 'G6', keyCode: '209', key: '', url: noteBaseUrl + 'a86.mp3', type: 'white'},
    {id: 11, name: 'A6', keyCode: '210', key: '', url: noteBaseUrl + 'a66.mp3', type: 'white'},
    {id: 23, name: 'B6', keyCode: '211', key: '', url: noteBaseUrl + 'a78.mp3', type: 'white'},
    {id: 22, name: 'C7', keyCode: '212', key: '', url: noteBaseUrl + 'a77.mp3', type: 'white'},
  
    {id: 36, name: 'C#2', keyCode: 'b49', key: '', url: noteBaseUrl + 'b49.mp3', type: 'black'},
    {id: 37, name: 'D#2', keyCode: 'b50', key: '', url: noteBaseUrl + 'b50.mp3', type: 'black'},
    {id: 38, name: 'F#2', keyCode: 'b52', key: '', url: noteBaseUrl + 'b52.mp3', type: 'black'},
    {id: 39, name: 'G#2', keyCode: 'b53', key: '', url: noteBaseUrl + 'b53.mp3', type: 'black'},
    {id: 40, name: 'A#2', keyCode: '90', key: 'z', url: noteBaseUrl + 'b54.mp3', type: 'black'},
    {id: 41, name: 'C#3', keyCode: '86', key: 'v', url: noteBaseUrl + 'b56.mp3', type: 'black'},
    {id: 42, name: 'D#3', keyCode: '188', key: ',', url: noteBaseUrl + 'b57.mp3', type: 'black'},
    {id: 43, name: 'F#3', keyCode: '85', key: 'u', url: noteBaseUrl + 'b81.mp3', type: 'black'},
    {id: 44, name: 'G#3', keyCode: '82', key: 'r', url: noteBaseUrl + 'b87.mp3', type: 'black'},
    {id: 45, name: 'A#3', keyCode: '73', key: 'i', url: noteBaseUrl + 'b69.mp3', type: 'black'},
    {id: 46, name: 'C#4', keyCode: '84', key: 't', url: noteBaseUrl + 'b84.mp3', type: 'black'},
    {id: 47, name: 'D#4', keyCode: '78', key: 'n', url: noteBaseUrl + 'b89.mp3', type: 'black'},
    {id: 48, name: 'F#4', keyCode: '67', key: 'c', url: noteBaseUrl + 'b73.mp3', type: 'black'},
    {id: 49, name: 'G#4', keyCode: '70', key: 'f', url: noteBaseUrl + 'b79.mp3', type: 'black'},
    {id: 50, name: 'A#4', keyCode: '80', key: 'p', url: noteBaseUrl + 'b80.mp3', type: 'black'},
    {id: 51, name: 'C#5', keyCode: '75', key: 'k', url: noteBaseUrl + 'b83.mp3', type: 'black'},
    {id: 52, name: 'D#5', keyCode: '191', key: '/', url: noteBaseUrl + 'b68.mp3', type: 'black'},
    {id: 53, name: 'F#5', keyCode: 'b71', key: '', url: noteBaseUrl + 'b71.mp3', type: 'black'},
    {id: 54, name: 'G#5', keyCode: 'b72', key: '', url: noteBaseUrl + 'b72.mp3', type: 'black'},
    {id: 55, name: 'A#5', keyCode: 'b74', key: '', url: noteBaseUrl + 'b74.mp3', type: 'black'},
    {id: 56, name: 'C#6', keyCode: 'b76', key: '', url: noteBaseUrl + 'b76.mp3', type: 'black'},
    {id: 57, name: 'D#6', keyCode: 'b90', key: '', url: noteBaseUrl + 'b90.mp3', type: 'black'},
    {id: 58, name: 'F#6', keyCode: 'b67', key: '', url: noteBaseUrl + 'b67.mp3', type: 'black'},
    {id: 59, name: 'G#6', keyCode: 'b86', key: '', url: noteBaseUrl + 'b86.mp3', type: 'black'},
    {id: 60, name: 'A#6', keyCode: 'b66', key: '', url: noteBaseUrl + 'b66.mp3', type: 'black'},
  ],
  pentatonic: [
    {id: 1, name: 'C2', keyCode: '86', key: 'v', url: noteBaseUrl + 'a49.mp3', type: 'white'},
    {id: 2, name: 'D2', keyCode: '80', key: 'p', url: noteBaseUrl + 'a50.mp3', type: 'white'},
    {id: 3, name: 'E2', keyCode: '71', key: 'g', url: noteBaseUrl + 'a51.mp3', type: 'white'},
    {id: 4, name: 'F2', keyCode: 'b49', key: '', url: noteBaseUrl + 'a52.mp3', type: 'white'},
    {id: 5, name: 'G2', keyCode: '87', key: 'w', url: noteBaseUrl + 'a53.mp3', type: 'white'},
    {id: 6, name: 'A2', keyCode: '85', key: 'u', url: noteBaseUrl + 'a54.mp3', type: 'white'},
    {id: 7, name: 'B2', keyCode: 'b50', key: '', url: noteBaseUrl + 'a55.mp3', type: 'white'},
    {id: 8, name: 'C3', keyCode: '76', key: 'l', url: noteBaseUrl + 'a56.mp3', type: 'white'},
    {id: 9, name: 'D3', keyCode: '82', key: 'r', url: noteBaseUrl + 'a57.mp3', type: 'white'},
    {id: 10, name: 'E3', keyCode: '83', key: 's', url: noteBaseUrl + 'a48.mp3', type: 'white'},
    {id: 26, name: 'F3', keyCode: 'b51', key: '', url: noteBaseUrl + 'a81.mp3', type: 'white'},
    {id: 32, name: 'G3', keyCode: '73', key: 'i', url: noteBaseUrl + 'a87.mp3', type: 'white'},
    {id: 14, name: 'A3', keyCode: '65', key: 'a', url: noteBaseUrl + 'a69.mp3', type: 'white'},
    {id: 27, name: 'B3', keyCode: 'b52', key: '', url: noteBaseUrl + 'a82.mp3', type: 'white'},
    {id: 29, name: 'C4', keyCode: '69', key: 'e', url: noteBaseUrl + 'a84.mp3', type: 'white'},
    {id: 34, name: 'D4', keyCode: '84', key: 't', url: noteBaseUrl + 'a89.mp3', type: 'white'},
    {id: 30, name: 'E4', keyCode: '79', key: 'o', url: noteBaseUrl + 'a85.mp3', type: 'white'},
    {id: 18, name: 'F4', keyCode: 'b53', key: '', url: noteBaseUrl + 'a73.mp3', type: 'white'},
    {id: 24, name: 'G4', keyCode: '78', key: 'n', url: noteBaseUrl + 'a79.mp3', type: 'white'},
    {id: 25, name: 'A4', keyCode: '72', key: 'h', url: noteBaseUrl + 'a80.mp3', type: 'white'},
    {id: 10, name: 'B4', keyCode: 'b54', key: '', url: noteBaseUrl + 'a65.mp3', type: 'white'},
    {id: 28, name: 'C5', keyCode: '68', key: 'd', url: noteBaseUrl + 'a83.mp3', type: 'white'},
    {id: 13, name: 'D5', keyCode: '67', key: 'c', url: noteBaseUrl + 'a68.mp3', type: 'white'},
    {id: 15, name: 'E5', keyCode: '77', key: 'm', url: noteBaseUrl + 'a70.mp3', type: 'white'},
    {id: 16, name: 'F5', keyCode: 'b55', key: '', url: noteBaseUrl + 'a71.mp3', type: 'white'},
    {id: 17, name: 'G5', keyCode: '70', key: 'f', url: noteBaseUrl + 'a72.mp3', type: 'white'},
    {id: 19, name: 'A5', keyCode: '89', key: 'y', url: noteBaseUrl + 'a74.mp3', type: 'white'},
    {id: 20, name: 'B5', keyCode: 'b56', key: '', url: noteBaseUrl + 'a75.mp3', type: 'white'},
    {id: 21, name: 'C6', keyCode: '66', key: 'b', url: noteBaseUrl + 'a76.mp3', type: 'white'},
    {id: 35, name: 'D6', keyCode: '75', key: 'k', url: noteBaseUrl + 'a90.mp3', type: 'white'},
    {id: 33, name: 'E6', keyCode: '74', key: 'j', url: noteBaseUrl + 'a88.mp3', type: 'white'},
    {id: 12, name: 'F6', keyCode: 'b57', key: '', url: noteBaseUrl + 'a67.mp3', type: 'white'},
    {id: 31, name: 'G6', keyCode: '88', key: 'x', url: noteBaseUrl + 'a86.mp3', type: 'white'},
    {id: 11, name: 'A6', keyCode: '81', key: 'q', url: noteBaseUrl + 'a66.mp3', type: 'white'},
    {id: 23, name: 'B6', keyCode: 'b58', key: '', url: noteBaseUrl + 'a78.mp3', type: 'white'},
    {id: 22, name: 'C7', keyCode: '90', key: 'z', url: noteBaseUrl + 'a77.mp3', type: 'white'},
  
    {id: 36, name: 'C#2', keyCode: 'b59', key: '', url: noteBaseUrl + 'b49.mp3', type: 'black'},
    {id: 37, name: 'D#2', keyCode: 'b60', key: '', url: noteBaseUrl + 'b50.mp3', type: 'black'},
    {id: 38, name: 'F#2', keyCode: 'b61', key: '', url: noteBaseUrl + 'b52.mp3', type: 'black'},
    {id: 39, name: 'G#2', keyCode: 'b62', key: '', url: noteBaseUrl + 'b53.mp3', type: 'black'},
    {id: 40, name: 'A#2', keyCode: 'b63', key: '', url: noteBaseUrl + 'b54.mp3', type: 'black'},
    {id: 41, name: 'C#3', keyCode: 'b64', key: '', url: noteBaseUrl + 'b56.mp3', type: 'black'},
    {id: 42, name: 'D#3', keyCode: 'b65', key: '', url: noteBaseUrl + 'b57.mp3', type: 'black'},
    {id: 43, name: 'F#3', keyCode: 'b66', key: '', url: noteBaseUrl + 'b81.mp3', type: 'black'},
    {id: 44, name: 'G#3', keyCode: 'b67', key: '', url: noteBaseUrl + 'b87.mp3', type: 'black'},
    {id: 45, name: 'A#3', keyCode: 'b68', key: '', url: noteBaseUrl + 'b69.mp3', type: 'black'},
    {id: 46, name: 'C#4', keyCode: 'b69', key: '', url: noteBaseUrl + 'b84.mp3', type: 'black'},
    {id: 47, name: 'D#4', keyCode: 'b70', key: '', url: noteBaseUrl + 'b89.mp3', type: 'black'},
    {id: 48, name: 'F#4', keyCode: 'b71', key: '', url: noteBaseUrl + 'b73.mp3', type: 'black'},
    {id: 49, name: 'G#4', keyCode: 'b72', key: '', url: noteBaseUrl + 'b79.mp3', type: 'black'},
    {id: 50, name: 'A#4', keyCode: 'b73', key: '', url: noteBaseUrl + 'b80.mp3', type: 'black'},
    {id: 51, name: 'C#5', keyCode: 'b74', key: '', url: noteBaseUrl + 'b83.mp3', type: 'black'},
    {id: 52, name: 'D#5', keyCode: 'b75', key: '', url: noteBaseUrl + 'b68.mp3', type: 'black'},
    {id: 53, name: 'F#5', keyCode: 'b76', key: '', url: noteBaseUrl + 'b71.mp3', type: 'black'},
    {id: 54, name: 'G#5', keyCode: 'b77', key: '', url: noteBaseUrl + 'b72.mp3', type: 'black'},
    {id: 55, name: 'A#5', keyCode: 'b78', key: '', url: noteBaseUrl + 'b74.mp3', type: 'black'},
    {id: 56, name: 'C#6', keyCode: 'b80', key: '', url: noteBaseUrl + 'b76.mp3', type: 'black'},
    {id: 57, name: 'D#6', keyCode: 'b81', key: '', url: noteBaseUrl + 'b90.mp3', type: 'black'},
    {id: 58, name: 'F#6', keyCode: 'b82', key: '', url: noteBaseUrl + 'b67.mp3', type: 'black'},
    {id: 59, name: 'G#6', keyCode: 'b83', key: '', url: noteBaseUrl + 'b86.mp3', type: 'black'},
    {id: 60, name: 'A#6', keyCode: 'b84', key: '', url: noteBaseUrl + 'b66.mp3', type: 'black'},
  ],
}
export const NotesMap = [
  { name: 'C2', file: 'a49.mp3' },
  { name: 'D2', file: 'a50.mp3' },
  { name: 'E2', file: 'a51.mp3' },
  { name: 'F2', file: 'a52.mp3' },
  { name: 'G2', file: 'a53.mp3' },
  { name: 'A2', file: 'a54.mp3' },
  { name: 'B2', file: 'a55.mp3' },
  { name: 'C3', file: 'a56.mp3' },
  { name: 'D3', file: 'a57.mp3' },
  { name: 'E3', file: 'a48.mp3' },
  { name: 'F3', file: 'a81.mp3' },
  { name: 'G3', file: 'a87.mp3' },
  { name: 'A3', file: 'a69.mp3' },
  { name: 'B3', file: 'a82.mp3' },
  { name: 'C4', file: 'a84.mp3' },
  { name: 'D4', file: 'a89.mp3' },
  { name: 'E4', file: 'a85.mp3' },
  { name: 'F4', file: 'a73.mp3' },
  { name: 'G4', file: 'a79.mp3' },
  { name: 'A4', file: 'a80.mp3' },
  { name: 'B4', file: 'a65.mp3' },
  { name: 'C5', file: 'a83.mp3' },
  { name: 'D5', file: 'a68.mp3' },
  { name: 'E5', file: 'a70.mp3' },
  { name: 'F5', file: 'a71.mp3' },
  { name: 'G5', file: 'a72.mp3' },
  { name: 'A5', file: 'a74.mp3' },
  { name: 'B5', file: 'a75.mp3' },
  { name: 'C6', file: 'a76.mp3' },
  { name: 'D6', file: 'a90.mp3' },
  { name: 'E6', file: 'a88.mp3' },
  { name: 'F6', file: 'a67.mp3' },
  { name: 'G6', file: 'a86.mp3' },
  { name: 'A6', file: 'a66.mp3' },
  { name: 'B6', file: 'a78.mp3' },
  { name: 'C7', file: 'a77.mp3' },

  { name: 'C#2', file: 'b49.mp3' },
  { name: 'D#2', file: 'b50.mp3' },
  { name: 'F#2', file: 'b52.mp3' },
  { name: 'G#2', file: 'b53.mp3' },
  { name: 'A#2', file: 'b54.mp3' },
  { name: 'C#3', file: 'b56.mp3' },
  { name: 'D#3', file: 'b57.mp3' },
  { name: 'F#3', file: 'b81.mp3' },
  { name: 'G#3', file: 'b87.mp3' },
  { name: 'A#3', file: 'b69.mp3' },
  { name: 'C#4', file: 'b84.mp3' },
  { name: 'D#4', file: 'b89.mp3' },
  { name: 'F#4', file: 'b73.mp3' },
  { name: 'G#4', file: 'b79.mp3' },
  { name: 'A#4', file: 'b80.mp3' },
  { name: 'C#5', file: 'b83.mp3' },
  { name: 'D#5', file: 'b68.mp3' },
  { name: 'F#5', file: 'b71.mp3' },
  { name: 'G#5', file: 'b72.mp3' },
  { name: 'A#5', file: 'b74.mp3' },
  { name: 'C#6', file: 'b76.mp3' },
  { name: 'D#6', file: 'b90.mp3' },
  { name: 'F#6', file: 'b67.mp3' },
  { name: 'G#6', file: 'b86.mp3' },
  { name: 'A#6', file: 'b66.mp3' }
]